--- name:default
# Camera emulator configuration options for Visual Odometry
cam_emu_confs:
  delay: 0.01
  start_index: 25
  img_dir: '/home/marta/Documents/myts/matteo_seq/'
  #img_dir: '/home/marta/Documents/devon/devon_usable/'
  right_dir: ''
  left_dir: ''
  left_mark: 'left'
  right_mark: 'right'
  img_file_format: '%s_%03d.jpg'

--- name:mapping
# Camera emulator configuration options for mapping
cam_emu_confs:
  delay: 0.01
  rotx: 0.0
  roty: 0.0
  rotz: 0.0
  trax: 0.0
  tray: 0.0
  traz: 0.0
  start_index: 0
  ## For original SPARTAN data
  #img_dir: '/home/marta/compass/software/vomap/src/build/sweep/input_data/'
  ## For SPARTAN data from VO path
  #img_dir: '/home/marta/compass/software/vomap/src/build/sweep/input_data/vo_path/'
  img_dir: '/home/marta/Documents/myts/mapping/lab_data/'
  right_dir: ''
  left_dir: ''
  left_mark: 'left'
  right_mark: 'right'
  img_file_format: '%s_%03d.jpg'
