%YAML:1.0
---
image_width: 512
image_height: 384
camera_matrix_1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [394.2054307, 0.0, 256, 0.0, 394.2054307, 192, 0.0, 0.0, 1.0]
distortion_coefficients_1: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
camera_matrix_2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [394.2054307, 0.0, 256, 0.0, 394.2054307, 192, 0.0, 0.0, 1.0]
distortion_coefficients_2: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
rotation_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
translation_coefficients: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.12, 0.0, 0.0]
