--- name:default
# the global name that should be used for the internal body frame
body_frame: body
# no documentation available for this property
calibration_confs:
  spartanWidth: 512
  spartanHeight: 384
  vertical: 1.0
  horizontal: 1.0
  shiftBot: 0.0
  ## Camera calibration (only uncomment one for the camera in use)
  calib_path: '/home/marta/rock/perception/orogen/spartan/config/exoter_loccam_calib.yaml'
  #calib_path: '/home/marta/rock/perception/orogen/spartan/config/hdpr_bb3_calib.yaml'
  #calib_path: '/home/marta/rock/perception/orogen/spartan/config/hdpr_bb2_ga_slam_tenerife.yaml'
  #calib_path: '/home/marta/rock/perception/orogen/spartan/config/navcam_calib.yaml'
  dump_file_path: ''
# the global name that should be used for the internal left_camera_viso2 frame
left_camera_viso2_frame: left_camera_viso2
# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.5
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
# desired period of the VO estimates (must be GREATER than the camera period)
# if set to 0.0 it will run as fast as it computes the motion estimate
desired_period: 5.0
# initial waiting time of the VO vomputation at startup
# recommended 8.0 sec for the navcam so it does not comput VO while the ptu moves
# it can be 0.0 sec for the loccam since it is fixed
wait_des: 0
# desired IFD to be achieved by changing the VO frequency. (good IFD = 0.1)
# Put -1.0 to disable the adaptive frequency and use the fixed period defined in "desired_period" in this same file
ifd_des: -1.0 #0.1
