--- name:default
# the global name that should be used for the internal body frame
body_frame: body
# no documentation available for this property
calibration_confs:
  spartanWidth: 1120
  spartanHeight: 1120
  vertical: 1.0
  horizontal: 1.0
  shiftBot: 0.0
  dump_file_path: ''    # Unused here
  # Except for this one
  ## For SPARTAN original test image pair
  #calib_path: '/home/marta/compass/software/vomap/src/build/sweep/input_data/mapping.yaml'
  ## For SPARTAN vo image pair
  #calib_path: '/home/marta/compass/software/vomap/src/build/sweep/input_data/vo_path/mapping_vo.yaml'
  ## For custom testing
  calib_path: '/home/marta/rock/perception/orogen/spartan/config/navcam_calib.yaml'
# the global name that should be used for the internal left_camera_viso2 frame
left_camera_viso2_frame: left_camera_viso2
# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.5
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
# no documentation available for this property
mapping_confs:
  ndepths: 301
  depthMode: 1  #0=LINEAR_DEPTHS, 1=EXPONENTIAL_DEPTHS
  matchKernelSide: 13
  mapWidth: 1120    #1120/horizontal
  mapHeight: 1120   #1120/vertical
  start_frame: 0
  dstart: 0.6
  dend: 10.0
  verticalDistance: 0.93
  horizontalDistance: 0.93
  gridStep: 0.000833
  xOffset: 0.0
  yOffset: 0.0
  correlationThresh: 0.8
  vertical: 1.0
  horizontal: 1.0
  shiftBot: 0.0
  truncNorm: 6.5
  voxelFactor: 0.5
  voxelSize: 0.035
  sniper1MinNeighbors: 5
  sniper1GrowthFactor: 5.5
  sniper1MinRadius: 0.1
  sniper1MaxRadius: 0.3
  sniper2MinNeighbors: 4
  sniper2GrowthFactor: 6
  sniper2MinRadius: 0.05
  sniper2MaxRadius: 0.15
  radNN: 4
  radRadius: 0.05
  includeColors: true
  calib_path: '/home/marta/rock/perception/orogen/spartan/config/navcam_calib.yaml'
  ## For SPARTAN original test image pair
  #calib_path: '/home/marta/compass/software/vomap/src/build/sweep/input_data/mapping.yaml'
  ## For SPARTAN vo image pair
  #calib_path: '/home/marta/compass/software/vomap/src/build/sweep/input_data/vo_path/mapping_vo.yaml'
  dump_file_path: ''
# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.5
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
