%YAML:1.0
---
image_width: 1120
image_height: 1120
camera_matrix_1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1200.92387548, 0.0, 560, 0.0, 1200.92387548, 560, 0.0, 0.0, 1.0]
distortion_coefficients_1: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
camera_matrix_2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1200.92387548, 0.0, 560, 0.0, 1200.92387548, 560, 0.0, 0.0, 1.0]
distortion_coefficients_2: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
rotation_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
translation_coefficients: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.2, 0.0, 0.0]
