--- name:default
# the global name that should be used for the internal body frame
body_frame: body
# no documentation available for this property
calibration_confs:
  spartanWidth: 512
  spartanHeight: 384
  vertical: 1.0
  horizontal: 1.0
  shiftBot: 0.0
  ## Exoter BB2 calibration
  calib_path: '/home/galar/Documents/myts/matteo_seq/custom_calib_v2.yaml'
  #calib_path: '/home/galar/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  dump_file_path: '/home/galar/Documents/devon/extra_files/rover-traverse-logs/vo_pose_estimations.txt'
# the global name that should be used for the internal left_camera_viso2 frame
left_camera_viso2_frame: left_camera_viso2
# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.5
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
